import { wizardDataToProfile, type WizardMasterData } from "@/lib/employee-wizard-mapper"
import type { EmployeeWizardData } from "@/types/employee-wizard"
import type { EmployeeProfile } from "@/types/employee-profile"
import type { ImportRow, ImportRowResult, ImportSummary } from "@/lib/employee-import/types"

/**
 * Injected instead of imported directly, so this module has zero
 * dependency on Next.js, React, or where employees are actually stored —
 * the explicit point of requirement 7 (background-job-ready). A future
 * queue worker calls importRows with the same three functions backed by
 * whatever the storage layer becomes (in-memory today, Prisma later)
 * without this file changing at all.
 */
export interface ImportServiceDependencies {
  isFinTaken: (finCode: string) => boolean
  isEmployeeNumberTaken: (employeeNumber: string) => boolean
  addEmployeeProfile: (profile: EmployeeProfile) => void
}

/**
 * Writes every row that passed validation, re-checking FIN/Employee Number
 * against the live directory at write time (not just the Preview-time
 * snapshot) — this is what makes import idempotent: re-running the exact
 * same file skips every row whose FIN already exists instead of creating a
 * duplicate. Rows blocked by a validation error are never attempted.
 */
export function importRows(
  rows: ImportRow[],
  masterData: WizardMasterData,
  deps: ImportServiceDependencies
): ImportRowResult[] {
  return rows.map((row) => {
    if (row.severity === "error") {
      return { ...row, outcome: "blocked" }
    }

    const finCode = row.mapped.finCode
    if (finCode && deps.isFinTaken(finCode)) {
      return { ...row, outcome: "skipped" }
    }

    const employeeNumber = row.mapped.employeeNumber ?? ""
    if (employeeNumber && deps.isEmployeeNumberTaken(employeeNumber)) {
      return { ...row, outcome: "skipped" }
    }

    const profile = wizardDataToProfile(row.mapped as EmployeeWizardData, masterData)
    deps.addEmployeeProfile(profile)

    return { ...row, outcome: "imported", employeeNumber: profile.employment.employeeNumber, employeeId: profile.id }
  })
}

export function summarizeImportResults(results: ImportRowResult[], durationMs: number): ImportSummary {
  return {
    totalRows: results.length,
    imported: results.filter((r) => r.outcome === "imported").length,
    skipped: results.filter((r) => r.outcome === "skipped").length,
    errors: results.filter((r) => r.severity === "error").length,
    warnings: results.filter((r) => r.severity === "warning").length,
    infos: results.filter((r) => r.messages.some((m) => m.severity === "info")).length,
    autoGeneratedEmployeeNumbers: results.filter((r) =>
      r.messages.some((m) => m.code === "EMPLOYEE_NUMBER_GENERATED")
    ).length,
    durationMs,
  }
}
