import { wizardDataToProfile, type WizardMasterData } from "@/lib/employee-wizard-mapper"
import type { EmployeeWizardData } from "@/types/employee-wizard"
import type { EmployeeProfile } from "@/types/employee-profile"
import type { ImportRow, ImportRowResult, ImportSettings, ImportSummary } from "@/lib/employee-import/types"

/**
 * Injected instead of imported directly, so this module has zero
 * dependency on Next.js, React, or where employees are actually stored —
 * the explicit point of requirement 7 (background-job-ready). A future
 * queue worker calls importRows with the same functions backed by
 * whatever the storage layer becomes (in-memory today, Prisma later)
 * without this file changing at all.
 */
export interface ImportServiceDependencies {
  isFinTaken: (finCode: string) => Promise<boolean>
  getEmployeeByFin: (finCode: string) => Promise<EmployeeProfile | null>
  isEmployeeNumberTaken: (employeeNumber: string) => Promise<boolean>
  addEmployeeProfile: (profile: EmployeeProfile) => Promise<void>
  updateEmployeeProfile: (id: string, profile: EmployeeProfile) => Promise<void>
}

/**
 * Writes every row that passed validation, re-checking FIN/Employee Number
 * against the live directory at write time (not just the Preview-time
 * snapshot). A FIN that already exists is Skip or Update per `settings`
 * (§14) rather than always skipped — on update, the existing record's own
 * id/employeeNumber are kept (an import never reassigns either), and its
 * payroll is kept or replaced per `settings.salaryStrategy` (§13). Rows
 * blocked by a validation error are never attempted.
 *
 * Rows are written one at a time, not in parallel — the dependencies now
 * read/write a real database, and an "is this employee number already
 * taken" check has to observe every row written before it in the same
 * chunk, not just the pre-chunk snapshot.
 */
export async function importRows(
  rows: ImportRow[],
  masterData: WizardMasterData,
  settings: ImportSettings,
  deps: ImportServiceDependencies
): Promise<ImportRowResult[]> {
  const results: ImportRowResult[] = []

  for (const row of rows) {
    if (row.severity === "error") {
      results.push({ ...row, outcome: "blocked" })
      continue
    }

    const finCode = row.mapped.finCode
    const existing = finCode ? await deps.getEmployeeByFin(finCode) : null

    if (existing) {
      if (settings.existingEmployeeStrategy === "skip") {
        results.push({ ...row, outcome: "skipped" })
        continue
      }

      const incoming = wizardDataToProfile(
        { ...row.mapped, employeeNumber: existing.employment.employeeNumber } as EmployeeWizardData,
        masterData
      )
      const keepSalary = settings.salaryStrategy === "keepExisting" && existing.payroll.baseSalary > 0
      const profile: EmployeeProfile = {
        ...incoming,
        id: existing.id,
        payroll: keepSalary ? existing.payroll : incoming.payroll,
      }
      await deps.updateEmployeeProfile(existing.id, profile)
      results.push({
        ...row,
        outcome: "updated",
        employeeNumber: profile.employment.employeeNumber,
        employeeId: profile.id,
      })
      continue
    }

    const employeeNumber = row.mapped.employeeNumber ?? ""
    if (employeeNumber && (await deps.isEmployeeNumberTaken(employeeNumber))) {
      results.push({ ...row, outcome: "skipped" })
      continue
    }

    const profile = wizardDataToProfile(row.mapped as EmployeeWizardData, masterData)
    await deps.addEmployeeProfile(profile)

    results.push({
      ...row,
      outcome: "imported",
      employeeNumber: profile.employment.employeeNumber,
      employeeId: profile.id,
    })
  }

  return results
}

function salaryOutcome(result: ImportRowResult): "created" | "updated" | "skipped" | "missing" {
  const hasExcelSalary = typeof result.mapped.baseSalary === "number" && result.mapped.baseSalary > 0
  if (result.outcome === "imported") return hasExcelSalary ? "created" : "missing"
  if (result.outcome === "updated") {
    if (!hasExcelSalary) return "missing"
    return result.messages.some((m) => m.code === "SALARY_WILL_UPDATE") ? "updated" : "skipped"
  }
  return "missing"
}

export function summarizeImportResults(results: ImportRowResult[], durationMs: number): ImportSummary {
  const salaryOutcomes = results.map(salaryOutcome)
  return {
    totalRows: results.length,
    imported: results.filter((r) => r.outcome === "imported").length,
    updated: results.filter((r) => r.outcome === "updated").length,
    skipped: results.filter((r) => r.outcome === "skipped").length,
    errors: results.filter((r) => r.severity === "error").length,
    warnings: results.filter((r) => r.severity === "warning").length,
    infos: results.filter((r) => r.messages.some((m) => m.severity === "info")).length,
    autoGeneratedEmployeeNumbers: results.filter((r) =>
      r.messages.some((m) => m.code === "EMPLOYEE_NUMBER_GENERATED")
    ).length,
    salary: {
      created: salaryOutcomes.filter((o) => o === "created").length,
      updated: salaryOutcomes.filter((o) => o === "updated").length,
      skipped: salaryOutcomes.filter((o) => o === "skipped").length,
      missing: salaryOutcomes.filter((o) => o === "missing").length,
    },
    durationMs,
  }
}
