import type { EmployeeWizardData } from "@/types/employee-wizard"

// ---------------------------------------------------------------------------
// Import is deliberately scoped to Personal + Employment fields — exactly
// what the approved validation rules cover (FIN, Employee Number,
// Department, Position, Company, Branch, Manager, dates, required fields).
// Labour Law / Payroll / Documents are left at wizardDataToProfile's own
// defaults, exactly as Create already does when a step is left untouched,
// and are editable later via Employee Edit.
//
// Department/Position/Company/Branch/Manager/WorkSchedule are text columns
// in the source file (names, not ids) — distinct from EmployeeWizardData's
// id-based fields. The row-mapper + master-data-resolver turn this text
// into the same id-based shape the wizard already uses, so
// wizardDataToProfile can be reused unmodified.
// ---------------------------------------------------------------------------
export type ImportableField =
  | "firstName"
  | "lastName"
  | "fatherName"
  | "gender"
  | "dateOfBirth"
  | "nationality"
  | "maritalStatus"
  | "finCode"
  | "nationalId"
  | "passportNumber"
  | "address"
  | "phone"
  | "email"
  | "emergencyContactName"
  | "emergencyContactPhone"
  | "emergencyContactRelation"
  | "employeeNumber"
  | "hireDate"
  | "probationEndDate"
  | "employmentType"
  | "contractType"
  | "department"
  | "position"
  | "company"
  | "branch"
  | "manager"
  | "workSchedule"
  | "workLocationType"
  | "workLocation"

export interface ColumnMapping {
  /** The literal header text found in the uploaded file. */
  excelColumn: string
  field: ImportableField | "ignore"
}

export type ImportSeverity = "info" | "warning" | "error"

export type ImportMessageCode =
  | "REQUIRED_FIELD_MISSING"
  | "INVALID_DATE"
  | "VALUE_NORMALIZED"
  | "EMPLOYEE_NUMBER_GENERATED"
  | "DUPLICATE_FIN_IN_FILE"
  | "DUPLICATE_EMPLOYEE_NUMBER_IN_FILE"
  | "DUPLICATE_EMPLOYEE_NUMBER_EXISTING"
  | "DUPLICATE_FIN_EXISTING"
  | "DEPARTMENT_NOT_FOUND"
  | "POSITION_NOT_FOUND"
  | "COMPANY_NOT_FOUND"
  | "BRANCH_NOT_FOUND"
  | "MANAGER_NOT_FOUND"
  | "WORK_SCHEDULE_CUSTOM"

export interface ImportRowMessage {
  code: ImportMessageCode
  severity: ImportSeverity
  field?: ImportableField
  message: string
}

/**
 * The unit both the Validate/Preview steps and the import service operate
 * on. `severity` is the highest severity among `messages` (error > warning
 * > info). `willImport` is false only when severity is "error" — every
 * other row is attempted at import time, including rows that will be
 * skipped for idempotency (willSkipAsDuplicate), which is a distinct,
 * non-error outcome.
 */
export interface ImportRow {
  rowNumber: number
  raw: Record<string, unknown>
  mapped: Partial<EmployeeWizardData>
  messages: ImportRowMessage[]
  severity: ImportSeverity
  willImport: boolean
  willSkipAsDuplicate: boolean
}

export type ImportRowOutcome = "imported" | "skipped" | "blocked"

export interface ImportRowResult extends ImportRow {
  outcome: ImportRowOutcome
  employeeNumber?: string
  employeeId?: string
}

export interface ImportSummary {
  totalRows: number
  imported: number
  skipped: number
  errors: number
  warnings: number
  infos: number
  autoGeneratedEmployeeNumbers: number
  durationMs: number
}

/** One row of the uploaded sheet before mapping/validation. */
export interface RawImportRow {
  rowNumber: number
  cells: Record<string, unknown>
}

export type ImportDraftStatus = "draft" | "completed"

export interface ImportDraft {
  id: string
  fileName: string
  createdAt: string
  updatedAt: string
  status: ImportDraftStatus
  sheetNames: string[]
  selectedSheet: string
  headerColumns: string[]
  columnMapping: ColumnMapping[]
  rawRows: RawImportRow[]
  /** Which of the 7 wizard steps the user had reached (0-indexed). */
  currentStep: number
}
