"use client"

import { useMemo, useState } from "react"
import { useTranslations } from "next-intl"
import { ChevronLeft, ChevronRight, Save } from "lucide-react"
import type { ColumnDef } from "@tanstack/react-table"

import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { DataTable } from "@/components/common/data-table"
import { getFullName } from "@/lib/employees"
import type { ImportRow } from "@/lib/employee-import/types"

type PreviewFilter = "all" | "errors" | "warnings" | "valid" | "changed" | "autoGenerated"

const PAGE_SIZE = 50

interface PreviewStepProps {
  rows: ImportRow[]
  onBack: () => void
  onNext: () => void
  onSaveDraft: () => void
}

function severityVariant(severity: ImportRow["severity"]) {
  if (severity === "error") return "destructive" as const
  if (severity === "warning") return "outline" as const
  return "secondary" as const
}

export function PreviewStep({ rows, onBack, onNext, onSaveDraft }: PreviewStepProps) {
  const t = useTranslations("Employees.import.preview")
  const [filter, setFilter] = useState<PreviewFilter>("all")
  const [pageIndex, setPageIndex] = useState(0)

  const counts = useMemo(
    () => ({
      all: rows.length,
      errors: rows.filter((r) => r.severity === "error").length,
      warnings: rows.filter((r) => r.severity === "warning").length,
      valid: rows.filter((r) => r.severity !== "error" && r.severity !== "warning").length,
      changed: rows.filter((r) => r.messages.some((m) => m.code === "VALUE_NORMALIZED")).length,
      autoGenerated: rows.filter((r) => r.messages.some((m) => m.code === "EMPLOYEE_NUMBER_GENERATED")).length,
    }),
    [rows]
  )

  const filtered = useMemo(() => {
    switch (filter) {
      case "errors":
        return rows.filter((r) => r.severity === "error")
      case "warnings":
        return rows.filter((r) => r.severity === "warning")
      case "valid":
        return rows.filter((r) => r.severity !== "error" && r.severity !== "warning")
      case "changed":
        return rows.filter((r) => r.messages.some((m) => m.code === "VALUE_NORMALIZED"))
      case "autoGenerated":
        return rows.filter((r) => r.messages.some((m) => m.code === "EMPLOYEE_NUMBER_GENERATED"))
      default:
        return rows
    }
  }, [rows, filter])

  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE))
  const currentPage = Math.min(pageIndex, pageCount - 1)
  const pageRows = filtered.slice(currentPage * PAGE_SIZE, currentPage * PAGE_SIZE + PAGE_SIZE)

  const columns: ColumnDef<ImportRow>[] = [
    { accessorKey: "rowNumber", header: t("columnRow"), cell: ({ row }) => row.original.rowNumber },
    {
      id: "name",
      header: t("columnName"),
      cell: ({ row }) => getFullName(row.original.mapped as { firstName: string; lastName: string }),
    },
    { id: "finCode", header: t("columnFin"), cell: ({ row }) => row.original.mapped.finCode || "—" },
    {
      id: "employeeNumber",
      header: t("columnEmployeeNumber"),
      cell: ({ row }) => row.original.mapped.employeeNumber || "—",
    },
    {
      id: "severity",
      header: t("columnSeverity"),
      cell: ({ row }) => (
        <Badge variant={severityVariant(row.original.severity)}>{t(`severity.${row.original.severity}`)}</Badge>
      ),
    },
    {
      id: "messages",
      header: t("columnMessages"),
      cell: ({ row }) => (
        <ul className="flex flex-col gap-0.5 text-xs text-muted-foreground">
          {row.original.messages.map((m, i) => (
            <li key={i}>{m.message}</li>
          ))}
        </ul>
      ),
    },
  ]

  const filterButtons: { key: PreviewFilter; label: string }[] = [
    { key: "all", label: t("filterAll", { count: counts.all }) },
    { key: "errors", label: t("filterErrors", { count: counts.errors }) },
    { key: "warnings", label: t("filterWarnings", { count: counts.warnings }) },
    { key: "valid", label: t("filterValid", { count: counts.valid }) },
    { key: "changed", label: t("filterChanged", { count: counts.changed }) },
    { key: "autoGenerated", label: t("filterAutoGenerated", { count: counts.autoGenerated }) },
  ]

  return (
    <div className="flex flex-col gap-4">
      <Card>
        <CardContent className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <h3 className="font-heading text-base font-semibold text-foreground">{t("title")}</h3>
            <p className="text-sm text-muted-foreground">{t("description")}</p>
          </div>

          <div className="flex flex-wrap items-center gap-1.5">
            {filterButtons.map((button) => (
              <Button
                key={button.key}
                size="sm"
                variant={filter === button.key ? "default" : "outline"}
                onClick={() => {
                  setFilter(button.key)
                  setPageIndex(0)
                }}
              >
                {button.label}
              </Button>
            ))}
          </div>

          <DataTable
            columns={columns}
            data={pageRows}
            emptyTitle={t("emptyTitle")}
            emptyDescription={t("emptyDescription")}
          />

          {filtered.length > PAGE_SIZE ? (
            <div className="flex items-center justify-between text-sm text-muted-foreground">
              <span>{t("pageIndicator", { current: currentPage + 1, total: pageCount })}</span>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={currentPage === 0}
                  onClick={() => setPageIndex((p) => Math.max(0, p - 1))}
                >
                  <ChevronLeft className="size-4" strokeWidth={1.75} />
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={currentPage >= pageCount - 1}
                  onClick={() => setPageIndex((p) => Math.min(pageCount - 1, p + 1))}
                >
                  <ChevronRight className="size-4" strokeWidth={1.75} />
                </Button>
              </div>
            </div>
          ) : null}
        </CardContent>
      </Card>

      <div className="flex items-center justify-between">
        <Button variant="outline" onClick={onBack}>
          {t("back")}
        </Button>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={onSaveDraft}>
            <Save className="size-4" strokeWidth={1.75} />
            {t("saveDraft")}
          </Button>
          <Button disabled={counts.errors === counts.all} onClick={onNext}>
            {t("next")}
            <ChevronRight className="size-4" strokeWidth={1.75} />
          </Button>
        </div>
      </div>
    </div>
  )
}
