"use client"

import { useTranslations } from "next-intl"
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  Download,
  FileWarning,
  Hash,
  Info,
  ListChecks,
  RefreshCcw,
  SkipForward,
} from "lucide-react"

import { Link } from "@/i18n/navigation"
import { Button, buttonVariants } from "@/components/ui/button"
import { KpiCard } from "@/components/common/kpi-card"
import { cn } from "@/lib/utils"
import { downloadImportReport } from "@/lib/employee-import/import-report"
import type { ImportRowResult, ImportSummary } from "@/lib/employee-import/types"

interface SummaryStepProps {
  summary: ImportSummary
  results: ImportRowResult[]
  fileName: string
}

export function SummaryStep({ summary, results, fileName }: SummaryStepProps) {
  const t = useTranslations("Employees.import.summary")

  const tiles = [
    { label: t("totalRows"), value: summary.totalRows, icon: Hash },
    { label: t("imported"), value: summary.imported, icon: CheckCircle2 },
    { label: t("updated"), value: summary.updated, icon: RefreshCcw },
    { label: t("skipped"), value: summary.skipped, icon: SkipForward },
    { label: t("errors"), value: summary.errors, icon: AlertTriangle },
    { label: t("warnings"), value: summary.warnings, icon: FileWarning },
    { label: t("infos"), value: summary.infos, icon: Info },
    { label: t("autoGeneratedEmployeeNumbers"), value: summary.autoGeneratedEmployeeNumbers, icon: ListChecks },
    { label: t("duration"), value: `${(summary.durationMs / 1000).toFixed(1)}s`, icon: Clock },
  ]

  const salaryTiles = [
    { label: t("salary.created"), value: summary.salary.created },
    { label: t("salary.updated"), value: summary.salary.updated },
    { label: t("salary.skipped"), value: summary.salary.skipped },
    { label: t("salary.missing"), value: summary.salary.missing },
  ]

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-1">
        <h3 className="font-heading text-lg font-semibold text-foreground">{t("title")}</h3>
        <p className="text-sm text-muted-foreground">{t("description")}</p>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {tiles.map((tile) => (
          <KpiCard key={tile.label} label={tile.label} value={String(tile.value)} icon={tile.icon} />
        ))}
      </div>

      <div className="flex flex-col gap-2">
        <h4 className="font-heading text-sm font-semibold text-foreground">{t("salary.title")}</h4>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {salaryTiles.map((tile) => (
            <div key={tile.label} className="rounded-lg border border-border p-3">
              <p className="text-xs text-muted-foreground">{tile.label}</p>
              <p className="text-lg font-semibold tabular-nums text-foreground">{tile.value}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          onClick={() => downloadImportReport(results, `import-report-${fileName.replace(/\.[^.]+$/, "")}.xlsx`)}
        >
          <Download className="size-4" strokeWidth={1.75} />
          {t("downloadReport")}
        </Button>
        <Link href="/employees" className={cn(buttonVariants())}>
          {t("backToEmployees")}
        </Link>
      </div>
    </div>
  )
}
